################################################################
# API and dashboard configuration
################################################################
[api]
################################################################
# Docker configuration backend
################################################################
#[docker]
#domain = "docker.local"
#watch = true

# We use file provider
[file]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[frontends]
  [frontends.frontend1]
  backend = "backend1"
    #[frontends.frontend1.routes.test]
    #rule = "Path:/test"

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://192.168.1.16:8081"
    weight = 1
    [backends.backend1.servers.server2]
    url = "http://192.168.1.16:8082"
    weight = 1
    [backends.backend1.servers.server3]
    url = "http://192.168.1.16:8083"
    weight = 1
